In [ ]:
from scrappers import NBAStatsScraper
# Scrape data from 2014 to 2024
for year in range(2004, 2010):
    for stats_type in ['per_game', 'advanced']:
        scraper = NBAStatsScraper(year=str(year), stats_type=stats_type)
        scraper.scrape_data()        
        scraper.save_to_csv()

NameError: name 'Scrapper' is not defined

In [38]:
# pip install lxml
import requests
from bs4 import BeautifulSoup
from io import StringIO
import pandas as pd
a = []



for n in range(0, 45*25, 25):
    if n%100 == 0:
        print(n)
    url = f"https://www.prosportstransactions.com/basketball/Search/SearchResults.php?Player=&Team=&BeginDate=2014-05-01&EndDate=2014-12-31&PlayerMovementChkBx=yes&Submit=Search&start={n}"

    response = requests.get(url)
    html = response.content
    soup = BeautifulSoup(html, 'lxml')
    table = soup.find('table', attrs={'class': 'datatable center'})
    table_str = str(table)

    # Use StringIO to read the string as if it were a file
    df = pd.read_html(StringIO(table_str), header=0)[0]
    free_agents = df[df['Notes'].str.contains('agen')]
    a.append(free_agents)

0
100
200
300
400
500
600
700
800
900
1000
1100

In [39]:
free_agents = pd.concat(a)
free_agents.Acquired = free_agents.Acquired.str.replace('•','') # remove • in front of player's name
free_agents.Relinquished = free_agents.Relinquished.str.replace('•','') # remove • in front of player's name

In [ ]:
free_agents.drp[free_agents.Acquired.str.contains('Duncan')]

ValueError: Cannot mask with non-boolean array containing NA / NaN values

In [53]:
aa = free_agents.dropna(subset=['Acquired'])
aa[aa.Acquired.str.contains('Delfino')]

Empty DataFrame
Columns: [Date, Team, Acquired, Relinquished, Notes]
Index: []

In [55]:
aa = free_agents.dropna(subset=['Relinquished'])
aa[aa.Relinquished.str.contains('Delfino')]

Empty DataFrame
Columns: [Date, Team, Acquired, Relinquished, Notes]
Index: []

In [50]:
pd.set_option('display.max_colwidth', None)

In [62]:
import re

# Define a function to extract year and money
def extract_year_money(notes):
    match = re.search(r'signed .* (\d+)-year.*\$(\d.*M)', notes)
    if match:
        return pd.Series([int(match.group(1)), match.group(2)])
    else:
        return pd.Series([None, None])

# Apply the function to the Notes column
free_agents[['Contract_Years', 'Contract_Value']] = free_agents['Notes'].apply(extract_year_money)

In [65]:
pd.set_option('display.max_rows', None)
free_agents[free_agents.Notes.str.contains('\$')]

,Date,Team,Acquired,Relinquished,Notes,Contract_Years,Contract_Value
18,2014-07-10,Blazers,Chris Kaman,NaN,signed unrestricted free agent to a 2-year $9.8M contract (second year is team option),2.0,9.8M
19,2014-07-10,Blazers,Steve Blake,NaN,signed unrestricted free agent to a 2-year $4.2M contract (second year is player option),2.0,4.2M
21,2014-07-10,Clippers,Jordan Farmar,NaN,signed unrestricted free agent to a 2-year $4.2M contract,2.0,4.2M
22,2014-07-10,Clippers,Spencer Hawes,NaN,signed unrestricted free agent to a 4-year $23M contract,4.0,23M
24,2014-07-10,Kings,Darren Collison,NaN,signed unrestricted free agent to a 3-year $16M contract,3.0,16M
1,2014-07-10,Raptors,James Johnson,NaN,signed unrestricted free agent to a 2-year $5M contract,2.0,5M
2,2014-07-10,Raptors,Kyle Lowry,NaN,re-signed unrestricted free agent to a 4-year $48M contract,4.0,48M
3,2014-07-10,Raptors,Patrick Patterson,NaN,re-signed restricted free agent to a 3-year $18M contract,3.0,18M
4,2014-07-10,Spurs,Patrick Mills / Patty Mills,NaN,re-signed unrestricted free agent to a 3-year $12M contract,3.0,12M
5,2014-07-10,Warriors,Shaun Livingston,NaN,signed unrestricted free agent to a 3-year $16M contract (third year is team option),3.0,16M
6,2014-07-10,Wizards,Marcin Gortat,NaN,re-signed unrestricted free agent to a 5-year $60M contract,5.0,60M
12,2014-07-11,Cavaliers,LeBron James,NaN,signed unrestricted free agent to a 2-year $42.1M contract (second year is player option),2.0,42.1M
13,2014-07-11,Grizzlies,Vince Carter,NaN,signed unrestricted free agent to a 3-year $12M contract,3.0,12M
18,2014-07-11,Magic,Ben Gordon,NaN,signed free agent to a 2-year $9M contract,2.0,9M
19,2014-07-11,Pacers,C.J. Miles,NaN,signed unrestricted free agent to a 4-year $18M contract,4.0,18M
0,2014-07-12,Jazz,Gordon Hayward,NaN,re-signed restricted free agent to a 4-year $63M contract (matched Hornets offer sheet),4.0,63M
2,2014-07-12,Kings,Isaiah Thomas,NaN,"re-signed restricted free agent to a 4-year, $27M contract",4.0,27M
7,2014-07-13,Heat,Chris Andersen,NaN,re-signed unrestricted free agent to a 2-year $10.4M contract,2.0,10.4M
9,2014-07-13,Knicks,Carmelo Anthony,NaN,re-signed unrestricted free agent to a 5-year $124M contract,5.0,124M
12,2014-07-13,Mavericks,Chandler Parsons,NaN,signed restricted free agent to a 3-year $46M contract (Rockets declined to match offer sheet),3.0,46M
14,2014-07-13,Pistons,Caron Butler,NaN,signed unrestricted free agent to a 2-year $9M contract (second year is team option),2.0,9M
15,2014-07-13,Pistons,D.J. Augustine,NaN,signed unrestricted free agent to a 2-year $2.6M contract,2.0,2.6M
17,2014-07-14,Heat,Danny Granger,NaN,"signed unrestricted free agent to a 2-year $4,2M contract",2.0,"4,2M"
18,2014-07-14,Heat,Josh McRoberts,NaN,signed unrestricted free agent to a 4-year $23M contract,4.0,23M
19,2014-07-14,Heat,Mario Chalmers,NaN,re-signed unrestricted free agent to a 2-year $8.3M contract,2.0,8.3M
20,2014-07-14,Magic,Channing Frye,NaN,"signed unrestricted free agent to a 4-year, $32M contract",4.0,32M
21,2014-07-14,Mavericks,Dirk Nowitzki,NaN,re-signed unrestricted free agent to a 3-year $30M contract (third year is player option),3.0,30M
24,2014-07-14,Pistons,Jodie Meeks,NaN,signed unrestricted free agent to a 3-year $19.5M contract,3.0,19.5M
1,2014-07-14,Wizards,Trevor Ariza,NaN,re-signed unrestricted free agent to a 4-year $32M contract,4.0,32M
13,2014-07-15,Celtics,Avery Bradley,NaN,re-signed restricted free agent on a 4-year $32M contract,4.0,32M
14,2014-07-15,Grizzlies,Beno Udrih,NaN,re-signed unrestricted free agent to a 2-year $4.2M contract,2.0,4.2M
15,2014-07-15,Heat,Dwyane Wade,NaN,re-signed unrestricted free agent to a 2-year $34M contract (second year is player option),2.0,34M
17,2014-07-15,Heat,Luol Deng,NaN,signed unrestricted free agent to a 2-year $20M contract,2.0,20M
19,2014-07-15,Nets,Alan Anderson,NaN,re-signed unrestricted free agent to a 2-year $3M contract (second year is player option),2.0,3M
21,2014-07-15,Spurs,Boris Diaw,NaN,"re-signed unrestricted free agent to a 3-year $22,5M contract (third year is team option)",3.0,"22,5M"
1,2014-07-15,Thunder,Thabo Sefolosha,NaN,re-signed unrestricted free agent to a 3-year $12M contract,3.0,12M
5,2014-07-16,Thunder,Anthony Morrow,NaN,signed unrestricted free agent to a 3-year $10M contract,3.0,10M
6,2014-07-16,Mavericks,DeJuan Blair,NaN,re-signed unrestricted free agent to a 3-year $6M contract,3.0,6M
11,2014-07-17,Mavericks,Devin Harris,NaN,re-signed unrestricted free agent to a 3-year $9M contract,3.0,9M
13,2014-07-17,Raptors,Greivis Vasquez,NaN,re-signed restricted free agent to a 2-year $13M contract,2.0,13M
14,2014-07-17,Wizards,Kevin Seraphin,NaN,re-signed restricted free agent to a 1-year $3.8M contract,1.0,3.8M
15,2014-07-17,Wizards,Paul Pierce,NaN,signed unrestricted free agent to a 2-year $11M contract,2.0,11M
17,2014-07-18,Bulls,Pau Gasol,NaN,signed unrestricted free agent to a 3-year $22M contract,3.0,22M
19,2014-07-18,Heat,Udonis Haslem,NaN,re-signed unrestricted free agent to a 2-year $5.6M contract,2.0,5.6M
20,2014-07-18,Hornets,Lance Stephenson,NaN,signed unrestricted free agent to a 3-year $27M contract,3.0,27M
21,2014-07-18,Knicks,Jason Smith,NaN,signed unrestricted free agent to a 1-year $3.3M contract,1.0,3.3M
9,2014-07-19,Celtics,Kris Humphries,NaN,"re-signed unrestricted free agent to a 3-year, $13M contract",3.0,13M
15,2014-07-21,Bulls,Kirk Hinrich,NaN,re-signed unrestricted free agent to a 2-year $5.5M contract (second year is player option),2.0,5.5M
16,2014-07-21,Hornets,Marvin Williams,NaN,signed unrestricted free agent to a 2-year $14M contract,2.0,14M
17,2014-07-21,Jazz,Trevor Booker,NaN,signed unrestricted free agent to a 2-year $10M contract,2.0,10M
18,2014-07-21,Lakers,Nick Young,NaN,re-signed unrestricted free agent to a 4-year $21.5M contract,4.0,21.5M
19,2014-07-21,Lakers,Ryan Kelly,NaN,re-signed restricted free agent to a 2-year $3.35M contract,2.0,3.35M
24,2014-07-21,Suns,Anthony Tolliver,NaN,signed unrestricted free agent to a 2-year $6M contract (second year is team option),2.0,6M
1,2014-07-22,Bulls,Aaron Brooks,NaN,signed unrestricted free agent to a 1-year $1.5M contract,1.0,1.5M
9,2014-07-22,Warriors,Brandon Rush,NaN,signed unrestricted free agent to a 2-year $2.5M contract (second year is player option),2.0,2.5M
12,2014-07-23,Hornets,Brian Roberts,NaN,signed unrestricted free agent to a 2-year $5.5M contract,2.0,5.5M
14,2014-07-23,Lakers,Ed Davis (Adam),NaN,signed unrestricted free agent to a 2-year $2M contract (second year is player option),2.0,2M
15,2014-07-23,Lakers,Jordan Hill,NaN,re-signed unrestricted free agent to a 2-year $18M contract (second year is team option),2.0,18M
20,2014-07-23,Suns,P.J. Tucker,NaN,re-signed restricted free agent to a 3-year $16.5M contract (third year is team option),3.0,16.5M
23,2014-07-24,Mavericks,Jameer Nelson (Sr.),NaN,signed free agent to a 2-year $6M contract (second year is player option),2.0,6M
1,2014-07-25,Hornets,Jannero Pargo,NaN,re-signed unrestricted free agent to a 1-year $1.5M contract,1.0,1.5M
4,2014-07-25,Magic,Luke Ridnour,NaN,signed unrestricted free agent to a 2-year $5.5M contract,2.0,5.5M
14,2014-07-29,Timberwolves,Maurice Williams / Mo Williams,NaN,signed unrestricted free agent to a 1-year $3.75M contract,1.0,3.75M
16,2014-07-30,Heat,Chris Bosh,NaN,re-signed unrestricted free agent to a 5-year $118M contract,5.0,118M
0,2014-07-31,Bucks,Jerryd Bayless,NaN,signed unrestricted free agent to a 2-year $6M contract,2.0,6M
18,2014-08-05,Cavaliers,Mike Miller,NaN,signed unrestricted free agent to a 2-year $5.5M contract (second year is player option),2.0,5.5M
20,2014-08-25,Hawks,(James) Mike Scott,NaN,re-signed restricted free agent to a 3-year $10M contract,3.0,10M
2,2014-08-26,Pelicans,John Salmons,NaN,signed free agent to a 1-year $2M contract,1.0,2M
16,2014-09-08,Pistons,Greg Monroe,NaN,re-signed restricted free agent to a 1-year $5.5M qualifying offer,1.0,5.5M
13,2014-09-22,Kings,Ramon Sessions,NaN,signed unrestricted free agent to a 2-year $4.2M contract,2.0,4.2M
18,2014-09-23,Hawks,Elton Brand,NaN,re-signed unrestricted free agent to a 1-year $4M contract,1.0,4M
19,2014-09-23,Hawks,Kent Bazemore,NaN,"signed unrestricted free agent to a 2-year, $4M contract",2.0,4M
19,2014-09-24,Suns,Eric Bledsoe,NaN,re-signed restricted free agent to a 5-year $70M contract,5.0,70M
23,2014-09-26,Spurs,Aron Baynes,NaN,re-signed restricted free agent to a 1-year $2.1M contract,1.0,2.1M
11,2014-09-29,Suns,Zoran Dragic,NaN,signed free agent to a 2-year $3.5M contract,2.0,3.5M

In [1]:
from scrappers import  FreeAgentScrapper, ContractScrapper

# Scrape data from 2014 to 2024
for year in range(2011, 2025):
    scraper = ContractScrapper(year=str(year), site='sportrac')
    scraper.scrape_data()
    scraper.save_to_csv()
    free_agents_scraper = FreeAgentScrapper(year=str(year))
    free_agents_dict = free_agents_scraper.scrape_data()
    free_agents_scraper.save_to_csv(free_agents_dict)

Scraping data for year 2011
Scraping data for year 2011 free agents
Scraping data for year 2012
Scraping data for year 2012 free agents
Scraping data for year 2013
Scraping data for year 2013 free agents
Scraping data for year 2014
Scraping data for year 2014 free agents
Scraping data for year 2015
Scraping data for year 2015 free agents
Scraping data for year 2016
Scraping data for year 2016 free agents
Scraping data for year 2017
Scraping data for year 2017 free agents
Scraping data for year 2018
Scraping data for year 2018 free agents
Scraping data for year 2019
Scraping data for year 2019 free agents
Scraping data for year 2020
Scraping data for year 2020 free agents
Scraping data for year 2021
Scraping data for year 2021 free agents
Scraping data for year 2022
Scraping data for year 2022 free agents
Scraping data for year 2023
Scraping data for year 2023 free agents
Scraping data for year 2024
Scraping data for year 2024 free agents